apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-ui
  template:
    metadata:
      labels:
        app: retail-ui
    spec:
      containers:
        - name: retail-ui
          image: public.ecr.aws/aws-containers/retail-store-sample-ui:1.3.0
          ports:
            - containerPort: 8080
          env:
            - name: RETAIL_UI_THEME
              value: "teal"

---
apiVersion: v1
kind: Service
metadata:
  name: retail-ui-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: retail-ui
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007