apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
type: Opaque
data:
  RETAIL_CATALOG_PERSISTENCE_USER: "bXlzcWxfdXNlcg=="   # base64 encoded value of "mysql_user"
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "Y2F0YWxvZzEyMw=="   # base64 encoded value of "catalog123"